### ISSUE TITLE
Is it time to remove or replace `crate-ci/typos`?

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/.github#130]
### Short Description

Following a recent change, `crate-ci/typos` is causing many false positives. For now, I have commented them out #129. We previously had https://github.com/codespell-project/codespell. Maybe something else or remove altogether?

**Comment by paddyroddy** [comment]
[v1.24.4](https://github.com/crate-ci/typos/discussions/1094) seems to have fixed most of the issues? 🤞

**Comment by ruaridhg** [comment]
> I don't know if this is related, but I'm getting a frustrating [linting error](https://github.com/UCL-MIRSG/mirsg-upgrades/actions/runs/10775358490/job/29879581234?pr=71) due to US/UK spelling since it wants to correct the US spelling of synchronize which is actually what is needed in the test.yml:
> 
> ```
> typos....................................................................Failed
> - hook id: typos
> - exit code: 2
> 
> error: `synchronize` should be `synchronise`
>   --> .github/workflows/tests.yml:15:9
>    |
> 15 |       - synchronize
>    |         ^^^^^^^^^^^
>    |
> ```

Updating my .pre-commit-config.yaml with the latest version worked for mirsg-upgrades:
```
repos:
  - repo: https://github.com/UCL-MIRSG/.github
    rev: v0.107.0
```

**Comment by paddyroddy** [comment]
> I don't know if this is related, but I'm getting a frustrating [linting error](https://github.com/UCL-MIRSG/mirsg-upgrades/actions/runs/10775358490/job/29879581234?pr=71) due to US/UK spelling since it wants to correct the US spelling of synchronize which is actually what is needed in the test.yml:
> 
> ```
> typos....................................................................Failed
> - hook id: typos
> - exit code: 2
> 
> error: `synchronize` should be `synchronise`
>   --> .github/workflows/tests.yml:15:9
>    |
> 15 |       - synchronize
>    |         ^^^^^^^^^^^
>    |
> ```

Yeah 100% related, as I said above `typos` has become a bit trigger happy. If nothing else we might want to remove this line https://github.com/UCL-MIRSG/.github/blob/ecd8fdc4f0f39b826fb6d7e97922d66a9929308f/precommit/mirsg-hooks.yaml#L79

**Comment by paddyroddy** [comment]
I think turning off British English (sad times) has solved this. It is very handy, so let's keep it.
