### ISSUE TITLE
Should we group all non-major renovate together

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/.github#136]
### Short Description

Should we default to grouping all non-major renovate updates together (by also extending from ["group:allNonMajor"](https://docs.renovatebot.com/presets-group/#groupallnonmajor) in the config)?

Benefit is fewer PRs to approve / merge and fewer CI minutes used.

Downside is it's potentially more difficult to troubleshoot issues with upgrades...

**Comment by paddyroddy** [comment]
Hmm... It could also cause confusion as to what broke what. I'd lean towards no, but happy to go with the consensus.

**Comment by paddyroddy** [comment]
Expanding this list https://github.com/UCL-ARC/.github/blob/d54aef9c76b43efbdbcb292a49954b45aac266cb/renovate/default-config.json#L18-L23 would also reduce noise

**Comment by paddyroddy** [comment]
I was sceptical, but actually I'm keen. Will do now.
