### ISSUE TITLE
🔥 [INCIDENT]: Linting will break MIRSG-wide on 01/02/2024

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/.github#90]
### Incident Description

This is more of a future warning, but due to some recent changes of hooks, various repos will fail their linting on 1st Feb (if using `mirsg-hooks`). This will be brought up in PRs so nothing to worry about.

### Resolution

Wait for the PRs to be raised, and fix.

### Root Cause

Following the (known) merge of #86, #88.

### Mitigation

Nothing, this is intended. However, worth letting people know. Shouldn't be much work, and hopefully for the better.

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
Did this end up causing issues as anticipated? Is there anything left to fix or shall we close?

**Comment by paddyroddy** [comment]
> Did this end up causing issues as anticipated? Is there anything left to fix or shall we close?

I'm not too sure. I did have to fix some, but was expecting more noise than happened. I think it's because there aren't actually too many repos using `mirsg-hooks`.

**Comment by HChughtai** [comment]
Can this be closed?

**Comment by paddyroddy** [comment]
Yeah

**Comment by paddyroddy** [comment]
I do think that due to UCL-ARC/.github#14, the aforementioned might now happen on 1st May. I've seen a fair few repos that were still on `v0.25.0` rather `v.0.60.0`. Now that we're archived a bunch (and hopefully more to come) this shouldn't be too much noise.
