### ISSUE TITLE
🙅 [PROBLEM]: IMO the MIRSG issue templates are not fit for purpose

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/.github#97]
### Problem Description

It is never clear to me what I should be using for a given issue. They need more descriptions so it is obvious to users to use. For example, this UCL-MIRSG/ansible-collection-infra#81 should probably be marked as a `question`... But I had to just look and pick one, which I'm not convinced was a great fit.

### Acceptance Criteria

```[tasklist]
### Related Work Items
```

**Comment by p-j-smith** [comment]
A `question` template would be good!

**Comment by HChughtai** [comment]
I'll look to simplfly these, and put forward a proposal for the group to review

**Comment by HChughtai** [comment]
Resovled by #106 and UCL-MIRSG/MIRSG#186
