### ISSUE TITLE
🐛 [BUG]: Hadolint pre-commit hook always fails if a Dockerfile is present

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/.github#98]
### Bug Description

The Hadolint pre-commit hook always fails with this error message:

```shell
Hadolint.................................................................Failed
- hook id: hadolint
- exit code: -11
```

### Steps to Reproduce

Make a Dockerfile and `git add` it to this repo. Then run pre-commit:

```
echo "FROM ubuntu:22.04" >> Dockerfile
git add Dockerfile
pre-commit run -a
```

Note, Hadolint doesn't fail if you install it (`brew install hadolint`) and run manually against this file:

```shell
hadolint Dockerfile
```

### Acceptance Criteria

The Hadolint pre-commit hook doesn't fail unless using the Hadolint command directly also fails.

```[tasklist]
### Related Work Items
```

**Comment by paddyroddy** [comment]
I used it without issues (and with `Dockerfiles`) in [SRR](https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/c4c191eec3b8fd22642ce4cda9a761fb214dc5c8/.pre-commit-config.yaml#L3-L6). Can you specify which version of `mirsg-hooks` you are using?

**Comment by p-j-smith** [comment]
not sure why this is happening - it's only an issue on my desktop not my laptop, so much be something to do with my setup. Sorry for the noise!
